from enum import Enum

class word_list(Enum):

    NUTRITION = "nutrition"
    FACT = "facts"
    SERVING = "serving"
    SIZE = "size"
    AMOUNT_PER_SERVING = "amount"
    ABOUT = "about"
    PER = "per"
    CALORIES = "calories"
    FROM = "from"
    DAILY = "daily"
    VALUE = "value"
    TOTAL = "total"
    FAT= "fat"
    SATURATED = "saturated"
    TRANS = "trans"
    CHOLESTEROL = "cholesterol"
    SODIUM = "sodium"
    CARBOHYDRATE = "carbohydrate"
    DIETARY = "dietary"
    FIBER = "fiber"
    SUGARS = "sugars"
    PROTEIN = "protein"
    VITAMIN= "vitamin"
    IRON = "iron"
    POSTASSIUM = "potassium"

    # NUTRITION_FACT = "Nutrition Facts"
    # SERVING_SIZE = "Serving size"
    # AMOUNT_PER_SERVING = "Amount per serving"
    # CALORIES = "Calories"
    # CALORIES_FROM_FAT = "Calories from Fat"
    # DAILY_VALUE = "% Daily Value"
    # TOTAL_FAT = "Total Fat"
    # SATURATED_FAT = "Saturated Fat"
    # TRANS_FAT = "Trans Fat"
    # CHOLESTEROL = "Cholesterol"
    # SODIUM = "Sodium"
    # TOTAL_CARBOHYDRATE = "Total Carbohydrate"
    # DIETARY_FIBER = "Dietary Fiber"
    # SUGARS = "Sugars"
    # PROTEIN = "Protein"
    # VITAMIN_A = "Vitamin A"
    # VITAMIN_B = "Vitamin B"
    # VITAMIN_C = "Vitamin C"
    # VITAMIN_D = "Vitamin D"
    # IRON = "Iron"
    # POSTASSIUM = "Potassium"
